Feature/geo json bounding box
missioncommand/emp3-android pull request #12
Opened 2017-02-08 20:25 UTC by rsupnekar

Fixed for multipolygons and features not starting with 'feature'

2017-02-08 20:49 UTC, ee11cbb19052e40b07aac0ca060c23ee commented on sdk/sdk-api/src/main/java/mil/emp3/json/geoJson/GeoJsonParser.java
> +            ioe.printStackTrace();
> ioe.printStackTrace();

Likely is not needed. Assumption would be that whomever is invoking this method would handle either the exception or log it or something else.

2017-02-08 20:52 UTC, ee11cbb19052e40b07aac0ca060c23ee commented on tests/basic/src/main/java/mil/emp3/dev_test_sdk/MainActivity.java
>                      e.printStackTrace();
Likely better to throw the exception than trap it.

2017-02-08 20:53 UTC, ee11cbb19052e40b07aac0ca060c23ee commented on tests/basic/src/main/java/mil/emp3/dev_test_sdk/MainActivity.java
> +                    camera.setAltitude(5e5);
```
camera.setLatitude(44.5);
camera.setLongitude(1);
camera.setAltitude(5e5);
```

Do these coordinates represent anything in particular?

2017-02-08 20:54 UTC, ee11cbb19052e40b07aac0ca060c23ee commented on tests/basic/src/main/java/mil/emp3/dev_test_sdk/MainActivity.java
> +                    stream.close();
> stream.close();

Better to have in finally block.

2017-02-08 20:54 UTC, ee11cbb19052e40b07aac0ca060c23ee commented on tests/basic/src/main/java/mil/emp3/dev_test_sdk/MainActivity.java
> +                    stream.close();
> stream.close();

Better to have in finally block.

2017-02-08 20:54 UTC, ee11cbb19052e40b07aac0ca060c23ee commented on tests/basic/src/main/java/mil/emp3/dev_test_sdk/MainActivity.java
> +                    stream.close();
> stream.close();

Better to have in finally block.

2017-02-08 20:57 UTC, ee11cbb19052e40b07aac0ca060c23ee requested changes
Improve exception handling and include comments for magic numbers (the coordinate values).

2017-02-09 13:12 UTC, Ish-rivera reviewed
Fix stream closing.

2017-02-09 14:35 UTC, ee11cbb19052e40b07aac0ca060c23ee approved these changes

2017-02-09 14:36 UTC, merged