Feature/emp3 android#11 display kml service data
missioncommand/emp3-android pull request #220
Opened 2017-04-27 15:40 UTC by empbarney

2017-04-27 16:34 UTC, ee11cbb19052e40b07aac0ca060c23ee commented
see #11

2017-04-27 17:30 UTC, Ish-rivera approved these changes
Fix the typo

2017-04-27 17:30 UTC, Ish-rivera commented on sdk/sdk-core/aar/src/main/java/mil/emp3/core/services/kml/KMLSRequest.java
> +public class KMLSRequest implements KMZFile.IKMZFileRerquest, IKMLSRequest {
Typo IKMZFileRerquest?

2017-04-27 17:30 UTC, Ish-rivera commented on sdk/sdk-core/aar/src/main/java/mil/emp3/core/services/kml/KMZFile.java
> +    public interface IKMZFileRerquest {
Typo IKMZFileRerquest

2017-04-27 17:36 UTC, ee11cbb19052e40b07aac0ca060c23ee requested changes

2017-04-27 17:36 UTC, ee11cbb19052e40b07aac0ca060c23ee commented on mapengine/worldwind/apk/src/main/java/mil/emp3/worldwind/layer/KMLServiceLayer.java
> +    final static private String TAG = KMLLayer.class.getSimpleName();
> final static private String TAG = KMLLayer.class.getSimpleName();

should be :
> final static private String TAG = KMLServiceLayer.class.getSimpleName();

2017-04-27 17:36 UTC, ee11cbb19052e40b07aac0ca060c23ee commented on sdk/sdk-api/src/main/java/mil/emp3/api/KML.java
> +     * @param documentBase A valid filesystem path (e.g. where KMZ fro adding of KML Service was exploded)
Typo:
> where KMZ fro adding of KML Service was exploded

2017-04-27 17:36 UTC, ee11cbb19052e40b07aac0ca060c23ee commented on sdk/sdk-api/src/main/java/mil/emp3/api/abstracts/MapService.java
> +        if(null != mapServiceURL) {
Do we want to provide the class name as part of this string?

2017-04-27 17:36 UTC, ee11cbb19052e40b07aac0ca060c23ee commented on sdk/sdk-api/src/main/java/mil/emp3/api/utils/kml/EmpKMLParser.java
> +                            URL url = new URL(kmlStyle.getIconUrl());
```url``` is not referenced
> URL url = new URL(kmlStyle.getIconUrl());

2017-04-27 17:36 UTC, ee11cbb19052e40b07aac0ca060c23ee commented on sdk/sdk-core/aar/src/main/java/mil/emp3/core/services/kml/KMLSProvider.java
> +     * @return
What does the return value signify?

2017-04-27 17:36 UTC, ee11cbb19052e40b07aac0ca060c23ee commented on sdk/sdk-core/aar/src/main/java/mil/emp3/core/services/kml/KMLSProvider.java
> +     * @return
What does the return value signify?

2017-04-27 17:36 UTC, ee11cbb19052e40b07aac0ca060c23ee commented on sdk/sdk-core/aar/src/main/java/mil/emp3/core/services/kml/KMLSProvider.java
> +                            Log.i(TAG, "KMLProcessor-run " + e.getMessage(), e);
Log.e instead here ?
> Log.i(..

2017-04-27 17:36 UTC, ee11cbb19052e40b07aac0ca060c23ee commented on sdk/sdk-core/aar/src/main/java/mil/emp3/core/services/kml/KMLSRequest.java
> +            return null;
What are the implications of the service having a null geoId?

2017-04-27 17:36 UTC, ee11cbb19052e40b07aac0ca060c23ee commented on sdk/sdk-core/aar/src/main/java/mil/emp3/core/services/kml/KMLSRequest.java
> +                try (InputStream input = connection.getInputStream();
Might be able to reduce some code with following:
>  java.nio.file.Files.copy(InputStream, Path, CopyOption...)

2017-04-27 17:36 UTC, ee11cbb19052e40b07aac0ca060c23ee commented on sdk/sdk-core/aar/src/main/java/mil/emp3/core/storage/MapStatus.java
> +        if(this.mapServiceHash.containsKey(uuid)) {
Can simplify to:
> return this.mapServiceHash.containsKey(uuid);

2017-04-27 17:36 UTC, ee11cbb19052e40b07aac0ca060c23ee commented on sdk/sdk-core/aar/src/main/java/mil/emp3/core/storage/StorageManager.java
> +        KMLSRequest.listKmlsRoot();
Maybe add a check for the logging level?
```java
if (Log.isLoggable(TAG, Log.VERBOSE)) {
    KMLSRequest.listKmlsRoot();
}
```

2017-04-27 17:36 UTC, ee11cbb19052e40b07aac0ca060c23ee commented on sdk/sdk-view/build.gradle
> +    testCompile "org.robolectric:robolectric:3.3.2"
> testCompile "org.robolectric:robolectric:3.3.2"

Declaration of dependency versions should be done in ```common.gradle```.

2017-04-27 17:36 UTC, ee11cbb19052e40b07aac0ca060c23ee commented on tests/test-vandv/src/main/java/mil/emp3/test/emp3vv/navItems/kml_service_test/KMLServiceTest.java
> +            "https://developers.google.com/kml/documentation/KML_Samples.kml"
```
 "https://github.com/downloads/brazzy/nikki/example.kmz",
 "https://developers.google.com/kml/documentation/KML_Samples.kml"
```
I wonder if we should add these as local testing resources.

2017-04-27 18:10 UTC, empbarney commented on sdk/sdk-core/aar/src/main/java/mil/emp3/core/services/kml/KMLSRequest.java
> +public class KMLSRequest implements KMZFile.IKMZFileRerquest, IKMLSRequest {
Fixed.

2017-04-27 18:11 UTC, empbarney commented on mapengine/worldwind/apk/src/main/java/mil/emp3/worldwind/layer/KMLServiceLayer.java
> +    final static private String TAG = KMLLayer.class.getSimpleName();
Done

2017-04-27 18:12 UTC, empbarney commented on sdk/sdk-api/src/main/java/mil/emp3/api/KML.java
> +     * @param documentBase A valid filesystem path (e.g. where KMZ fro adding of KML Service was exploded)
Done.

2017-04-27 18:16 UTC, empbarney commented on sdk/sdk-api/src/main/java/mil/emp3/api/abstracts/MapService.java
> +        if(null != mapServiceURL) {
No, sub class will print it's own name. MapService is abstract. I updated KMLS toString to call suprt.toString().

2017-04-27 18:18 UTC, empbarney commented on sdk/sdk-api/src/main/java/mil/emp3/api/utils/kml/EmpKMLParser.java
> +                            URL url = new URL(kmlStyle.getIconUrl());
Fixed.

2017-04-27 18:20 UTC, empbarney commented on sdk/sdk-core/aar/src/main/java/mil/emp3/core/services/kml/KMLSProvider.java
> +     * @return
if service was added then returns true else returns false. updated code.

2017-04-27 18:22 UTC, empbarney commented on sdk/sdk-core/aar/src/main/java/mil/emp3/core/services/kml/KMLSProvider.java
> +                            Log.i(TAG, "KMLProcessor-run " + e.getMessage(), e);
Fixed.

2017-04-27 18:24 UTC, empbarney commented on sdk/sdk-core/aar/src/main/java/mil/emp3/core/services/kml/KMLSRequest.java
> +            return null;
This not service having null geoId, this is checking if service itself is null. This should never happen. But I don't want to crash the APP.

2017-04-27 18:25 UTC, empbarney commented on sdk/sdk-core/aar/src/main/java/mil/emp3/core/services/kml/KMLSRequest.java
> +                try (InputStream input = connection.getInputStream();
Take a look at this comment on line 126, NIO was ending abruptly, so decided to go the long way, it is working reliably.

// Following would be much more efficient but it is truncating the file. If we have to support
        // Large file sizes then we should investigate the code below.

        // URL website = new URL("http://www.website.com/information.asp");
        // ReadableByteChannel rbc = Channels.newChannel(website.openStream());
        // FileOutputStream fos = new FileOutputStream("information.html");
        // fos.getChannel().transferFrom(rbc, 0, Long.MAX_VALUE);

2017-04-27 18:27 UTC, empbarney commented on sdk/sdk-core/aar/src/main/java/mil/emp3/core/storage/MapStatus.java
> +        if(this.mapServiceHash.containsKey(uuid)) {
Done.

2017-04-27 18:29 UTC, empbarney commented on sdk/sdk-core/aar/src/main/java/mil/emp3/core/storage/StorageManager.java
> +        KMLSRequest.listKmlsRoot();
Done.

2017-04-27 18:33 UTC, empbarney commented on sdk/sdk-view/build.gradle
> +    testCompile "org.robolectric:robolectric:3.3.2"
Done.

2017-04-27 18:34 UTC, empbarney commented on tests/test-vandv/src/main/java/mil/emp3/test/emp3vv/navItems/kml_service_test/KMLServiceTest.java
> +            "https://developers.google.com/kml/documentation/KML_Samples.kml"
These specifically hard coded for usability. There is support in VandV to build a File URL from files in /sdcard/testFiles. Additionally one can provide a URL by choosing the "CutomURL" option.

2017-04-27 18:37 UTC, empbarney commented on sdk/sdk-core/aar/src/main/java/mil/emp3/core/services/kml/KMLSProvider.java
> +     * @return
Updated.

2017-04-27 18:38 UTC, empbarney commented on sdk/sdk-core/aar/src/main/java/mil/emp3/core/services/kml/KMZFile.java
> +    public interface IKMZFileRerquest {
Fixed.

2017-04-27 19:37 UTC, ee11cbb19052e40b07aac0ca060c23ee approved these changes

2017-04-28 19:45 UTC, mubinakhan commented
Reintegrate

2017-04-28 19:50 UTC, merged