Closes issue #324 , adding github templates.
missioncommand/emp3-android pull request #371
Opened 2017-11-13 21:04 UTC by jrummel

Took templates from https://github.com/stevemao/github-issue-templates

If we want specific changes (i.e. a screenshot section) just say the word.

2017-11-20 18:39 UTC, stevendlander requested changes

2017-11-20 18:39 UTC, stevendlander commented on .github/ISSUE_TEMPLATE.md
> +  1.
2 & 3?

2017-11-27 16:48 UTC, jrummel commented on .github/ISSUE_TEMPLATE.md
> +  1.
Fixed.

2017-11-27 17:52 UTC, stevendlander approved these changes

2017-11-27 18:10 UTC, merged