#338 unit test circle
missioncommand/emp3-android pull request #385
Opened 2017-11-28 14:55 UTC by matt-miller-rgi

2017-11-28 15:15 UTC, stevendlander requested changes

2017-11-28 15:15 UTC, stevendlander commented on sdk/sdk-api/src/main/java/mil/emp3/api/Circle.java
> +import mil.emp3.api.utils.GeoLibrary;
GeoLibrary should be deprecated, you will need to use GeographicLib for this class.

2017-11-28 15:15 UTC, stevendlander commented on sdk/sdk-api/src/main/java/mil/emp3/api/Circle.java
> +        //seeting renderable bypasses radius validation
Seeting?

2017-11-29 18:41 UTC, JACochran requested changes

2017-11-29 18:41 UTC, JACochran commented on sdk/sdk-view/src/test/java/mil/emp3/api/CircleTest.java
> +    public void NaNSetRadius() {
all methods should be camel-cased so the "N" should be lowercase

2017-11-29 18:41 UTC, JACochran commented on sdk/sdk-view/src/test/java/mil/emp3/api/CircleTest.java
> +    public void NaNRadiusConstructor() {
N should be lowercase

2017-11-29 18:41 UTC, JACochran commented on sdk/sdk-view/src/test/java/mil/emp3/api/CircleTest.java
> +    public void NegativeRadiusConstructor() {
N should be lowercase

2017-12-01 15:25 UTC, stevendlander approved these changes

2017-12-01 15:25 UTC, JACochran approved these changes

2017-12-01 15:29 UTC, merged