Bug/#58 geojson feature
missioncommand/emp3-android pull request #64
Opened 2017-03-06 19:59 UTC by rsupnekar

2017-03-07 16:12 UTC, Ish-rivera commented on sdk/sdk-api/src/main/java/mil/emp3/api/interfaces/IGeoJSON.java
> +    List<IImageLayer> getImageLayerList();
I don't recall GeoJSON having images.  Also Update the javaDoc comments.

2017-03-07 16:14 UTC, Ish-rivera requested changes
I don't recall GeoJSON having images. Update all javaDoc comments.

2017-03-08 18:23 UTC, Ish-rivera approved these changes

2017-03-08 18:46 UTC, rsupnekar commented
Test is similar to the previous geoJSON test, except this time we navigate to it from the Add Remove Get option.  From there, Add Overlay.  Then Add Feature.  In the feature type list, select GEOJSON.  Then pick from the list of files.

2017-03-08 19:57 UTC, merged