Added GeoJSON export
missioncommand/emp3-android pull request #89
Opened 2017-03-21 16:40 UTC by rsupnekar

Added a menu item to export features

2017-03-21 16:44 UTC, ee11cbb19052e40b07aac0ca060c23ee commented on tests/test-vandv/src/main/java/mil/emp3/test/emp3vv/navItems/AddRemoveGetTest.java
> +                List<IFeature> featureList = maps[whichMap].getAllFeatures();
indentation off

2017-03-21 16:45 UTC, ee11cbb19052e40b07aac0ca060c23ee commented on tests/test-vandv/src/main/java/mil/emp3/test/emp3vv/navItems/AddRemoveGetTest.java
> +                        FileOutputStream fos = new FileOutputStream(file);
add a try-with-resources statement

2017-03-21 16:45 UTC, ee11cbb19052e40b07aac0ca060c23ee commented on tests/test-vandv/src/main/java/mil/emp3/test/emp3vv/navItems/AddRemoveGetTest.java
> +                        fos.close();
place into finally clause

2017-03-21 16:47 UTC, ee11cbb19052e40b07aac0ca060c23ee commented on tests/test-vandv/src/main/java/mil/emp3/test/emp3vv/navItems/AddRemoveGetTest.java
> +                            boolean created = file.createNewFile();
do we care if this value is false?
> boolean created = file.createNewFile();

2017-03-21 16:59 UTC, ee11cbb19052e40b07aac0ca060c23ee submitted a review, later dismissed

2017-03-21 17:33 UTC, rsupnekar commented
To test, build branch and run test-vandv.  From Add Remove Get, create an overlay and some features (circle, polygon, line, etc.).  Then from the feature menu, select export features to GeoJSON.  Features exported will appear as files in /sdcard/Download/<featurename>Geo.json.

Pull the files to your PC, using adb pull.  Open each file, copy and paste the contents on this web page and validate;

http://jsonlint.com/

2017-03-21 19:58 UTC, mubinakhan commented
Reintegrate

2017-03-28 11:42 UTC, ee11cbb19052e40b07aac0ca060c23ee requested changes
Minor changes:
* Change usage of InvalidParameterException to IllegalArgumentException

2017-03-28 11:42 UTC, ee11cbb19052e40b07aac0ca060c23ee commented on sdk/sdk-api/src/main/java/mil/emp3/json/geoJson/GeoJsonCaller.java
> +import java.security.InvalidParameterException;
Change to IllegalArgumentException
> import java.security.InvalidParameterException;

2017-03-28 11:42 UTC, ee11cbb19052e40b07aac0ca060c23ee commented on sdk/sdk-api/src/main/java/mil/emp3/json/geoJson/GeoJsonCaller.java
> +            throw new InvalidParameterException("Parameters can't be null.");
Change to IllegalArgumentException
> throw new InvalidParameterException("Parameters can't be null.");

2017-03-28 11:42 UTC, ee11cbb19052e40b07aac0ca060c23ee commented on sdk/sdk-api/src/main/java/mil/emp3/json/geoJson/GeoJsonCaller.java
> +            throw new InvalidParameterException("Parameters can't be null.");
Change to IllegalArgumentException
> throw new InvalidParameterException("Parameters can't be null.");

2017-03-28 11:51 UTC, ee11cbb19052e40b07aac0ca060c23ee approved these changes

2017-03-28 14:40 UTC, merged