Completely refactored
missioncommand/emp3-android pull request #9
Opened 2017-02-06 20:20 UTC by rsupnekar

Bounding box is not used in EMP feature.

This fixes the timestamp and timespan properties

2017-02-06 20:24 UTC, ee11cbb19052e40b07aac0ca060c23ee commented on sdk/sdk-api/src/main/java/mil/emp3/json/geoJson/GeoJsonParser.java
> +
maybe log a warning message here

2017-02-06 20:27 UTC, ee11cbb19052e40b07aac0ca060c23ee commented on sdk/sdk-api/src/main/java/mil/emp3/json/geoJson/GeoJsonParser.java
> +                    e.printStackTrace();
This methods throws a ParseException, why catch it here?

2017-02-06 20:28 UTC, ee11cbb19052e40b07aac0ca060c23ee requested changes
see comments

2017-02-07 13:08 UTC, Ish-rivera commented on sdk/sdk-api/src/main/java/mil/emp3/json/geoJson/GeoJsonParser.java
> +                    e.printStackTrace();
Same.

2017-02-07 13:46 UTC, ee11cbb19052e40b07aac0ca060c23ee approved these changes

2017-02-07 14:50 UTC, mubinakhan commented
https://github.com/orgs/missioncommand/projects/3
________________________________
From: rsupnekar [notifications@github.com]
Sent: Tuesday, February 07, 2017 9:45 AM
To: missioncommand/emp3-android
Cc: Khan, Mubina I CIV USARMY SEC (US); Mention
Subject: [Non-DoD Source] Re: [missioncommand/emp3-android] geoJSON BoundingBox - Completely refactored (#9)

All active links contained in this email were disabled. Please verify the identity of the sender, and confirm the authenticity of all links contained within the message prior to copying and pasting the address to a Web browser.

________________________________



Assigned #9 < Caution-https://github.com/missioncommand/emp3-android/pull/9 >  to @mubinakhan < Caution-https://github.com/mubinakhan > .

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub < Caution-https://github.com/missioncommand/emp3-android/pull/9#event-952172851 > , or mute the thread < Caution-https://github.com/notifications/unsubscribe-auth/AYTgg9y_PmtaDxX5YFKlbcB3MW3zhECpks5raIOLgaJpZM4L4q6D > .

2017-02-07 16:54 UTC, mubinakhan commented
FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':tests:test-basic:compileDebugJavaWithJavac'.
> Compilation failed; see the compiler error output for details.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED

2017-02-07 19:48 UTC, mubinakhan commented
![screenshot_20170207-143315 1](https://cloud.githubusercontent.com/assets/25485443/22708491/73c417e6-ed44-11e6-9575-6f4452a52a88.png)

2017-02-07 19:48 UTC, mubinakhan commented
Reintegrate

2017-02-07 19:55 UTC, merged

2017-02-08 20:14 UTC, mubinakhan commented
![screenshot_20170208-151341 1](https://cloud.githubusercontent.com/assets/25485443/22755474/497e3854-ee11-11e6-8cc2-f15277396e43.png)
![screenshot_20170208-151420 1](https://cloud.githubusercontent.com/assets/25485443/22755479/4fc04644-ee11-11e6-9256-b35df7514ef3.png)